-- IS-Connect database schema
-- Run in Supabase Dashboard -> SQL Editor, then run seed.sql.
-- Re-running this file drops and recreates every table (all data is lost).

drop table if exists items cascade;              -- old connection-test table
drop table if exists user_blocks cascade;
drop table if exists study_resources cascade;
drop table if exists meetups cascade;
drop table if exists availability_slots cascade;
drop table if exists messages cascade;
drop table if exists friendships cascade;
drop table if exists student_skills cascade;
drop table if exists skills cascade;
drop table if exists students cascade;

-- A person using the app (Make Account / Find Friends screens)
create table students (
  id                    uuid primary key default gen_random_uuid(),
  user_id               uuid unique default auth.uid() references auth.users(id) on delete cascade, -- login that owns this profile (null for sample students)
  full_name             text not null,
  avatar_url            text,
  program_status        text not null check (program_status in ('pre_is', 'is_core')),
  current_course        text,                 -- e.g. 'IS 201'
  looking_for_help_with text,
  bio                   text,
  created_at            timestamptz not null default now()
);

-- An IS strength a student can list on their profile (Python, SQL, ...)
create table skills (
  id   bigint generated by default as identity primary key,
  name text not null unique
);

-- Join table: students <-> skills (many-to-many)
create table student_skills (
  student_id uuid   not null references students(id) on delete cascade,
  skill_id   bigint not null references skills(id)   on delete cascade,
  primary key (student_id, skill_id)
);

-- Friend connection between two students
create table friendships (
  id           bigint generated by default as identity primary key,
  requester_id uuid not null references students(id) on delete cascade,
  addressee_id uuid not null references students(id) on delete cascade,
  status       text not null default 'pending' check (status in ('pending', 'accepted')),
  created_at   timestamptz not null default now(),
  unique (requester_id, addressee_id),
  check (requester_id <> addressee_id)
);

-- One-on-one chat message
create table messages (
  id           bigint generated by default as identity primary key,
  sender_id    uuid not null references students(id) on delete cascade,
  recipient_id uuid not null references students(id) on delete cascade,
  body         text not null,
  sent_at      timestamptz not null default now()
);

-- Weekly time a student is free to study (Calendar screen)
create table availability_slots (
  id               bigint generated by default as identity primary key,
  student_id       uuid not null references students(id) on delete cascade,
  day_of_week      text not null check (day_of_week in ('Mon','Tue','Wed','Thu','Fri','Sat','Sun')),
  start_time       time not null,
  duration_minutes int  not null default 60 check (duration_minutes > 0)
);

-- Study session between two students (Set Up / Confirm Meetup screens)
create table meetups (
  id           bigint generated by default as identity primary key,
  requester_id uuid not null references students(id) on delete cascade,
  partner_id   uuid not null references students(id) on delete cascade,
  scheduled_at timestamptz not null,
  location     text not null,
  status       text not null default 'requested'
               check (status in ('requested', 'confirmed', 'completed', 'cancelled')),
  created_at   timestamptz not null default now()
);

-- Student-made study guide / file shared with others (Upload Docs screen)
create table study_resources (
  id           bigint generated by default as identity primary key,
  uploader_id  uuid not null references students(id) on delete cascade,
  title        text not null,
  course       text,
  resource_url text not null,
  uploaded_at  timestamptz not null default now()
);

-- Block or report of another student (Block/Report screen)
create table user_blocks (
  id         bigint generated by default as identity primary key,
  blocker_id uuid not null references students(id) on delete cascade,
  blocked_id uuid not null references students(id) on delete cascade,
  is_report  boolean not null default false,
  reason     text,
  created_at timestamptz not null default now(),
  unique (blocker_id, blocked_id)
);

-- Row Level Security
-- Anyone may read every table. Only a logged-in user may create or edit
-- their own profile (students.user_id = auth.uid()) and its strengths.
alter table students           enable row level security;
alter table skills             enable row level security;
alter table student_skills     enable row level security;
alter table friendships        enable row level security;
alter table messages           enable row level security;
alter table availability_slots enable row level security;
alter table meetups            enable row level security;
alter table study_resources    enable row level security;
alter table user_blocks        enable row level security;

create policy "Public read" on students           for select to anon, authenticated using (true);
create policy "Public read" on skills             for select to anon, authenticated using (true);
create policy "Public read" on student_skills     for select to anon, authenticated using (true);
create policy "Public read" on friendships        for select to anon, authenticated using (true);
create policy "Public read" on messages           for select to anon, authenticated using (true);
create policy "Public read" on availability_slots for select to anon, authenticated using (true);
create policy "Public read" on meetups            for select to anon, authenticated using (true);
create policy "Public read" on study_resources    for select to anon, authenticated using (true);
create policy "Public read" on user_blocks        for select to anon, authenticated using (true);

create policy "Create own profile" on students for insert to authenticated with check (user_id = auth.uid());
create policy "Edit own profile"   on students for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "Add own skills" on student_skills for insert to authenticated
  with check (student_id in (select id from students where user_id = auth.uid()));
create policy "Remove own skills" on student_skills for delete to authenticated
  using (student_id in (select id from students where user_id = auth.uid()));
